#data
dataset_path: "/kaggle/input/datasets/sadhliroomyprime/football-semantic-segmentation/images"
color_map_path: "/kaggle/working/UNet-Assignment/color_map.json"
train_ratio: 0.8
n_classes: 11
new_size: 256



#model
lr: 0.0005
epochs: 50
level: -1
batch_size: 192