#data
dataset_path: "/kaggle/input/datasets/sadhliroomyprime/football-semantic-segmentation/images"
color_map_path: "/kaggle/working/UNet-Assignment/color_map.json"
train_ratio: 0.8
n_classes: 11




#model
lr: 0.001
epochs: 20
level: -1
batch_size: 32